#!/usr/bin/env sh

classes=("ProductApi:Product"
         "CartApi:Cart"
         "CheckoutApi:Checkout"
         "OrderApi:Order"
         "ServiceApi:Service")


         for i in `find ./lib/commerce/api -iname '*.rb'`; do

           for class in "${classes[@]}" ; do
               OLD=${class%%:*}
               NEW=${class#*:}
               sed -i '' -e "s/$OLD/$NEW/g" $i;
           done
         done


         fileNames=("product_api:product"
                    "cart_api:cart"
                    "checkout_api:checkout"
                    "order_api:order"
                    "service_api:service")

                    for filename in "${fileNames[@]}" ; do
                        OLD=${filename%%:*}
                        NEW=${filename#*:}
                        mv "lib/commerce/api/$OLD.rb" "lib/commerce/$NEW.rb"  2> /dev/null
                    done



                      for fileName in "${fileNames[@]}" ; do
                          OLD=${fileName%%:*}
                          NEW=${fileName#*:}.rb
                          sed -i '' -e "s/api\/$OLD/$NEW/g" lib/commerce.rb;
                      done



#Remove files we're not Using
rm -rf "commerce/docs"
rm -rf "commerce/spec"
rm -rf "lib/commerce/api"
rm "lib/commerce/api_client.rb"
rm "lib/commerce/api_error.rb"
rm "lib/commerce/configuration.rb"
rm "lib/commerce/version.rb"
rm "git_push.sh"
rm "README.md"
